# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Classpath' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!
  # Pods for Classpath
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FBSDKCoreKit', '~>4.34.0'
  pod 'FBSDKLoginKit', '~>4.34.0'
  pod 'FBSDKShareKit', '~>4.34.0'
  pod 'TwitterKit'
  pod 'SKPhotoBrowser'
  pod 'Gallery'
  pod 'Stripe'
  pod 'VerticalProgressView'
  pod 'STKWebKitViewController'
  pod 'FirebaseUI/Storage'
  pod 'SDWebImage'
  pod 'Google-Mobile-Ads-SDK', '~>7.41.0'
end
